/**
 * Browser Backend — Client-side fallback for vanity NPUB grinding.
 *
 * Phase 5 implementation.
 *
 * When no server-side compute backend (GPU, Rana) is available, the server
 * returns instructions and self-contained JavaScript code that the client
 * can run in their browser using @noble/secp256k1. The code uses the same
 * incremental offset grinding approach as demo/index.html Section 6:
 *
 *   P + d·G  for d = 1, 2, 3, ...
 *
 * The server never sees the user's secret key. The client applies the offset
 * locally: new_nsec = (old_nsec + d) mod n.
 *
 * @see docs/IMPLEMENTATION-PLAN.md Phase 5
 * @see demo/index.html Section 6 (lines 1620–1755) for the original browser code
 */

import type { GrindBackend, GrindParams, GrindResult } from "../types.js";

// ─── Bech32 encoding (self-contained, no external deps) ───────────────────

const BECH32_CHARSET = "qpzry9x8gf2tvdw0s3jn54khce6mua7l";

function bech32Polymod(values: number[]): number {
  const GEN = [0x3b6a57b2, 0x26508e6d, 0x1ea119fa, 0x3d4233dd, 0x2a1462b3];
  let chk = 1;
  for (const v of values) {
    const b = chk >> 25;
    chk = ((chk & 0x1ffffff) << 5) ^ v;
    for (let i = 0; i < 5; i++) {
      if ((b >> i) & 1) chk ^= GEN[i];
    }
  }
  return chk;
}

function bech32HrpExpand(hrp: string): number[] {
  const ret: number[] = [];
  for (const c of hrp) ret.push(c.charCodeAt(0) >> 5);
  ret.push(0);
  for (const c of hrp) ret.push(c.charCodeAt(0) & 31);
  return ret;
}

function bech32CreateChecksum(hrp: string, data: number[]): number[] {
  const values = bech32HrpExpand(hrp).concat(data);
  const polymod = bech32Polymod(values.concat([0, 0, 0, 0, 0, 0])) ^ 1;
  const ret: number[] = [];
  for (let i = 0; i < 6; i++) ret.push((polymod >> (5 * (5 - i))) & 31);
  return ret;
}

function convertBits(data: number[], fromBits: number, toBits: number, pad: boolean): number[] {
  let acc = 0;
  let bits = 0;
  const ret: number[] = [];
  const maxv = (1 << toBits) - 1;
  const maxAcc = (1 << (fromBits + toBits - 1)) - 1;
  for (const value of data) {
    if (value < 0 || value >> fromBits) throw new Error("Invalid value");
    acc = ((acc << fromBits) | value) & maxAcc;
    bits += fromBits;
    while (bits >= toBits) {
      bits -= toBits;
      ret.push((acc >> bits) & maxv);
    }
  }
  if (pad) {
    if (bits) ret.push((acc << (toBits - bits)) & maxv);
  } else if (bits >= fromBits || ((acc << (toBits - bits)) & maxv)) {
    throw new Error("Invalid padding");
  }
  return ret;
}

function bech32Encode(hrp: string, data8bit: Uint8Array): string {
  const data5bit = convertBits(Array.from(data8bit), 8, 5, true);
  const combined = data5bit.concat(bech32CreateChecksum(hrp, data5bit));
  return hrp + "1" + combined.map((v) => BECH32_CHARSET[v]).join("");
}

// ─── Browser grind code snippet generator ──────────────────────────────────

/**
 * Generate the self-contained JavaScript code that a client can run in their
 * browser to grind a vanity NPUB offset using @noble/secp256k1.
 *
 * The code is extracted and adapted from demo/index.html Section 6 (offset
 * grinding). It uses incremental EC point addition (currentPoint += G) for
 * efficiency — one point addition per offset rather than a full scalar
 * multiplication.
 *
 * @param npub - The user's public key (npub1...)
 * @param vanityPattern - The vanity word to search for
 * @param suffixPattern - Optional suffix pattern (null if none)
 * @param timeoutSecs - Maximum grind time in seconds
 * @returns A string containing the self-contained JS code
 */
export function generateBrowserGrindCode(
  npub: string,
  vanityPattern: string,
  suffixPattern: string | null,
  timeoutSecs: number,
): string {
  const suffixJs = suffixPattern ? `"${suffixPattern}"` : "null";
  const timeoutMs = timeoutSecs * 1000;

  return `// ─── Vanity NPUB Offset Grinding (browser-side) ───────────────────────
// Generated by VNAAS Grinder Server — Phase 5 browser fallback.
// Uses @noble/secp256k1 for EC point operations.
// Your secret key NEVER leaves your device. The server only saw your public key.
//
// Usage:
//   npm install @noble/secp256k1
//   node grind.mjs   (or paste into browser console with esm.sh import)
//
// After finding an offset d, apply it:
//   new_nsec = (your_nsec + d) mod n
//   new_npub = bech32((k + d) * G)  // should match vanity_npub

import { ProjectivePoint, utils, CURVE } from '@noble/secp256k1';

// ─── Bech32 encoding (BIP-173) ─────────────────────────────────────────
const CHARSET = 'qpzry9x8gf2tvdw0s3jn54khce6mua7l';

function bech32Polymod(values) {
  const GEN = [0x3b6a57b2, 0x26508e6d, 0x1ea119fa, 0x3d4233dd, 0x2a1462b3];
  let chk = 1;
  for (const v of values) {
    const b = chk >> 25;
    chk = ((chk & 0x1ffffff) << 5) ^ v;
    for (let i = 0; i < 5; i++) {
      if ((b >> i) & 1) chk ^= GEN[i];
    }
  }
  return chk;
}

function bech32HrpExpand(hrp) {
  const ret = [];
  for (const c of hrp) ret.push(c.charCodeAt(0) >> 5);
  ret.push(0);
  for (const c of hrp) ret.push(c.charCodeAt(0) & 31);
  return ret;
}

function bech32CreateChecksum(hrp, data) {
  const values = bech32HrpExpand(hrp).concat(data);
  const polymod = bech32Polymod(values.concat([0,0,0,0,0,0])) ^ 1;
  const ret = [];
  for (let i = 0; i < 6; i++) ret.push((polymod >> (5 * (5 - i))) & 31);
  return ret;
}

function convertBits(data, fromBits, toBits, pad) {
  let acc = 0, bits = 0;
  const ret = [];
  const maxv = (1 << toBits) - 1;
  const maxAcc = (1 << (fromBits + toBits - 1)) - 1;
  for (const value of data) {
    if (value < 0 || (value >> fromBits)) throw new Error('Invalid value');
    acc = ((acc << fromBits) | value) & maxAcc;
    bits += fromBits;
    while (bits >= toBits) {
      bits -= toBits;
      ret.push((acc >> bits) & maxv);
    }
  }
  if (pad) {
    if (bits) ret.push((acc << (toBits - bits)) & maxv);
  } else if (bits >= fromBits || ((acc << (toBits - bits)) & maxv)) {
    throw new Error('Invalid padding');
  }
  return ret;
}

function bech32Encode(hrp, data8bit) {
  const data5bit = convertBits(Array.from(data8bit), 8, 5, true);
  const combined = data5bit.concat(bech32CreateChecksum(hrp, data5bit));
  return hrp + '1' + combined.map(v => CHARSET[v]).join('');
}

function bech32Decode(str) {
  const pos = str.lastIndexOf('1');
  const hrp = str.substring(0, pos);
  const dataPart = str.substring(pos + 1);
  const data = [];
  for (const c of dataPart) {
    const v = CHARSET.indexOf(c);
    if (v === -1) throw new Error('Invalid char');
    data.push(v);
  }
  const values = bech32HrpExpand(hrp).concat(data);
  if (bech32Polymod(values) !== 1) throw new Error('Invalid checksum');
  const dataNoChk = data.slice(0, data.length - 6);
  return convertBits(dataNoChk, 5, 8, false);
}

// ─── Helpers ───────────────────────────────────────────────────────────
function bigIntTo32Bytes(val) {
  let hex = val.toString(16);
  while (hex.length < 64) hex = '0' + hex;
  const arr = new Uint8Array(32);
  for (let i = 0; i < 32; i++) {
    arr[i] = parseInt(hex.substring(i * 2, i * 2 + 2), 16);
  }
  return arr;
}

function checkVanity(npub, word, suffix) {
  const dataPart = npub.substring(5); // after "npub1"
  const lower = dataPart.toLowerCase();
  if (!lower.includes(word.toLowerCase())) return false;
  if (suffix && !lower.endsWith(suffix.toLowerCase())) return false;
  return true;
}

// ─── Configuration ─────────────────────────────────────────────────────
const USER_NPUB = "${npub}";
const VANITY_PATTERN = "${vanityPattern}";
const SUFFIX_PATTERN = ${suffixJs};
const TIMEOUT_MS = ${timeoutMs};

// ─── Offset Grinding ───────────────────────────────────────────────────
// Uses incremental point addition: currentPoint += G (one EC point add per step)
// This is the same approach as demo/index.html Section 6.

// Decode the user's NPUB to 32-byte x-only public key
const pubKeyBytes = bech32Decode(USER_NPUB);
if (pubKeyBytes.length !== 32) throw new Error('NPUB must decode to 32 bytes');

// Construct the user's public key point P from x-only bytes (assume even y)
const compressed = new Uint8Array(33);
compressed[0] = 0x02; // even parity
compressed.set(pubKeyBytes, 1);
const userPoint = ProjectivePoint.fromHex(compressed);

// Generator point G
const G = ProjectivePoint.fromPrivateKey(1n);

// Grinding loop
let d = 0n;
let currentPoint = userPoint; // P + 0*G = P
const startTime = Date.now();
let count = 0;

console.log('Starting offset grinding...');
console.log('  NPUB:', USER_NPUB);
console.log('  Vanity pattern:', VANITY_PATTERN);
if (SUFFIX_PATTERN) console.log('  Suffix pattern:', SUFFIX_PATTERN);
console.log('  Timeout:', TIMEOUT_MS / 1000, 'seconds');

while (Date.now() - startTime < TIMEOUT_MS) {
  // Batch of 300 offsets per iteration (balance between speed and responsiveness)
  for (let i = 0; i < 300; i++) {
    d++;
    count++;
    // Incremental: currentPoint += G (one EC point addition per step)
    currentPoint = currentPoint.add(G);
    // Get x-only pubkey (32 bytes)
    const xBytes = bigIntTo32Bytes(currentPoint.x);
    const newNpub = bech32Encode('npub', xBytes);
    if (checkVanity(newNpub, VANITY_PATTERN, SUFFIX_PATTERN)) {
      const elapsed = (Date.now() - startTime) / 1000;
      const rate = Math.round(count / elapsed);
      console.log('\\n✓ FOUND!');
      console.log('  Offset d:', d.toString());
      console.log('  Vanity NPUB:', newNpub);
      console.log('  Keys tried:', count.toLocaleString());
      console.log('  Time:', elapsed.toFixed(1) + 's');
      console.log('  Rate:', rate.toLocaleString() + '/s');
      console.log('\\nTo apply:');
      console.log('  new_nsec = (your_nsec + ' + d.toString() + ') mod n');
      console.log('  new_npub should be:', newNpub);
      // Return the result
      const result = {
        status: 'found',
        offset: d.toString(),
        vanity_npub: newNpub,
        grind_stats: {
          keys_tried: count,
          duration_secs: elapsed,
          rate_per_sec: rate,
          backend: 'browser',
        },
      };
      console.log('\\nResult JSON:');
      console.log(JSON.stringify(result, null, 2));
      // Exit successfully
      if (typeof process !== 'undefined') process.exit(0);
      return result;
    }
  }
  // Progress update
  const elapsed = (Date.now() - startTime) / 1000;
  const rate = Math.round(count / elapsed);
  if (count % 3000 === 0) {
    console.log('  ... tried ' + count.toLocaleString() + ' offsets (' + rate.toLocaleString() + '/s, ' + elapsed.toFixed(0) + 's)');
  }
}

// Timeout
const elapsed = (Date.now() - startTime) / 1000;
const rate = Math.round(count / elapsed);
console.log('\\n✗ Timeout: no match found in ' + elapsed.toFixed(1) + 's');
console.log('  Total offsets tried:', count.toLocaleString());
console.log('  Rate:', rate.toLocaleString() + '/s');
console.log('  Consider a shorter pattern or longer timeout.');
const timeoutResult = {
  status: 'timeout',
  grind_stats: {
    keys_tried: count,
    duration_secs: elapsed,
    rate_per_sec: rate,
    backend: 'browser',
  },
};
console.log('\\nResult JSON:');
console.log(JSON.stringify(timeoutResult, null, 2));
if (typeof process !== 'undefined') process.exit(1);
return timeoutResult;`;
}

// ─── BrowserBackend class ──────────────────────────────────────────────────

/**
 * Browser fallback backend.
 *
 * This backend does not perform any server-side grinding. Instead, it returns
 * `use_client_fallback` status with self-contained JavaScript code that the
 * client can execute in their browser or Node.js environment using
 * @noble/secp256k1.
 *
 * The grinding code uses incremental EC point addition (P + d·G) — the same
 * algorithm as demo/index.html Section 6 — so the client's secret key never
 * leaves their device.
 */
export class BrowserBackend implements GrindBackend {
  readonly name = "browser" as const;
  readonly available = true; // Always available as fallback
  readonly estimatedRate = 200; // ~200 keys/sec in browser (conservative)

  /**
   * Health check — the browser fallback is always available.
   * @returns Always true
   */
  async healthCheck(): Promise<boolean> {
    return true;
  }

  /**
   * "Grind" by returning client-side grinding instructions.
   *
   * This does not perform any server-side computation. It generates a
   * self-contained JavaScript snippet that the client can run locally.
   *
   * @param params - Grinding parameters (pubKeyBytes, patterns, timeout, etc.)
   * @returns GrindResult with found=false and clientCode containing the JS snippet
   */
  async grind(params: GrindParams): Promise<GrindResult> {
    // Encode the public key bytes as an npub for the client code
    const npub = bech32Encode("npub", params.pubKeyBytes);

    // Extract patterns
    const vanityPattern = params.vanityPatterns[0] ?? "";
    const suffixPattern = params.suffixPatterns?.[0] ?? null;
    const timeoutSecs = Math.floor(params.timeoutMs / 1000);

    // Generate the self-contained client-side grinding code
    const clientCode = generateBrowserGrindCode(
      npub,
      vanityPattern,
      suffixPattern,
      timeoutSecs,
    );

    return {
      found: false,
      keysTried: 0,
      durationMs: 0,
      backend: "browser",
      fallbackReason:
        "No server-side GPU or CPU grinding backend available. " +
        "Run the included JavaScript code locally in your browser or Node.js " +
        "to grind a vanity NPUB offset using @noble/secp256k1.",
      clientCode,
    };
  }
}

/**
 * Singleton instance of the browser fallback backend.
 */
export const browserBackend = new BrowserBackend();